//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.SAP.TankDipPosting
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DippingDataDelivery", Namespace="http://TankDip.Pertamina.com/")]
    public partial class DippingDataDelivery : object
    {
        
        private string plantField;
        
        private string dipDateField;
        
        private string dipTimeField;
        
        private string dipTankField;
        
        private string dipEventField;
        
        private string dipOperationField;
        
        private string totalHeightField;
        
        private string totalHeightUOMField;
        
        private string waterHeightField;
        
        private string waterHeightUOMField;
        
        private string celciusMaterialTempField;
        
        private string celciusTestTempField;
        
        private string kglDensityField;
        
        private string shipmentField;
        
        private string deliveryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dipDate
        {
            get
            {
                return this.dipDateField;
            }
            set
            {
                this.dipDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dipTime
        {
            get
            {
                return this.dipTimeField;
            }
            set
            {
                this.dipTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dipTank
        {
            get
            {
                return this.dipTankField;
            }
            set
            {
                this.dipTankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dipEvent
        {
            get
            {
                return this.dipEventField;
            }
            set
            {
                this.dipEventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dipOperation
        {
            get
            {
                return this.dipOperationField;
            }
            set
            {
                this.dipOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string totalHeight
        {
            get
            {
                return this.totalHeightField;
            }
            set
            {
                this.totalHeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string totalHeightUOM
        {
            get
            {
                return this.totalHeightUOMField;
            }
            set
            {
                this.totalHeightUOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string waterHeight
        {
            get
            {
                return this.waterHeightField;
            }
            set
            {
                this.waterHeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string waterHeightUOM
        {
            get
            {
                return this.waterHeightUOMField;
            }
            set
            {
                this.waterHeightUOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string celciusMaterialTemp
        {
            get
            {
                return this.celciusMaterialTempField;
            }
            set
            {
                this.celciusMaterialTempField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string celciusTestTemp
        {
            get
            {
                return this.celciusTestTempField;
            }
            set
            {
                this.celciusTestTempField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string kglDensity
        {
            get
            {
                return this.kglDensityField;
            }
            set
            {
                this.kglDensityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string shipment
        {
            get
            {
                return this.shipmentField;
            }
            set
            {
                this.shipmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string delivery
        {
            get
            {
                return this.deliveryField;
            }
            set
            {
                this.deliveryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCode", Namespace="http://TankDip.Pertamina.com/")]
    public partial class ResponseCode : object
    {
        
        private string TypeField;
        
        private string CodeField;
        
        private string DescMsgField;
        
        private TankDipPosting.Quantity[] additionalQuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DescMsg
        {
            get
            {
                return this.DescMsgField;
            }
            set
            {
                this.DescMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TankDipPosting.Quantity[] additionalQuantity
        {
            get
            {
                return this.additionalQuantityField;
            }
            set
            {
                this.additionalQuantityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quantity", Namespace="http://TankDip.Pertamina.com/")]
    public partial class Quantity : object
    {
        
        private string UomField;
        
        private string QtyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Uom
        {
            get
            {
                return this.UomField;
            }
            set
            {
                this.UomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TankDip.Pertamina.com/", ConfigurationName="TankDipPosting.ZMM_TANKDIP_DELIVERYSoap")]
    public interface ZMM_TANKDIP_DELIVERYSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TankDip.Pertamina.com/DoPosting", ReplyAction="*")]
        TankDipPosting.DoPostingResponse DoPosting(TankDipPosting.DoPostingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TankDip.Pertamina.com/DoPosting", ReplyAction="*")]
        System.Threading.Tasks.Task<TankDipPosting.DoPostingResponse> DoPostingAsync(TankDipPosting.DoPostingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoPostingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoPosting", Namespace="http://TankDip.Pertamina.com/", Order=0)]
        public TankDipPosting.DoPostingRequestBody Body;
        
        public DoPostingRequest()
        {
        }
        
        public DoPostingRequest(TankDipPosting.DoPostingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TankDip.Pertamina.com/")]
    public partial class DoPostingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TankDipPosting.DippingDataDelivery dipData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public DoPostingRequestBody()
        {
        }
        
        public DoPostingRequestBody(TankDipPosting.DippingDataDelivery dipData, string User, string Password)
        {
            this.dipData = dipData;
            this.User = User;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoPostingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoPostingResponse", Namespace="http://TankDip.Pertamina.com/", Order=0)]
        public TankDipPosting.DoPostingResponseBody Body;
        
        public DoPostingResponse()
        {
        }
        
        public DoPostingResponse(TankDipPosting.DoPostingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://TankDip.Pertamina.com/")]
    public partial class DoPostingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TankDipPosting.ResponseCode DoPostingResult;
        
        public DoPostingResponseBody()
        {
        }
        
        public DoPostingResponseBody(TankDipPosting.ResponseCode DoPostingResult)
        {
            this.DoPostingResult = DoPostingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZMM_TANKDIP_DELIVERYSoapChannel : TankDipPosting.ZMM_TANKDIP_DELIVERYSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZMM_TANKDIP_DELIVERYSoapClient : System.ServiceModel.ClientBase<TankDipPosting.ZMM_TANKDIP_DELIVERYSoap>, TankDipPosting.ZMM_TANKDIP_DELIVERYSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZMM_TANKDIP_DELIVERYSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ZMM_TANKDIP_DELIVERYSoapClient.GetBindingForEndpoint(endpointConfiguration), ZMM_TANKDIP_DELIVERYSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZMM_TANKDIP_DELIVERYSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZMM_TANKDIP_DELIVERYSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZMM_TANKDIP_DELIVERYSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZMM_TANKDIP_DELIVERYSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZMM_TANKDIP_DELIVERYSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TankDipPosting.DoPostingResponse DoPosting(TankDipPosting.DoPostingRequest request)
        {
            return base.Channel.DoPosting(request);
        }
        
        public System.Threading.Tasks.Task<TankDipPosting.DoPostingResponse> DoPostingAsync(TankDipPosting.DoPostingRequest request)
        {
            return base.Channel.DoPostingAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZMM_TANKDIP_DELIVERYSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ZMM_TANKDIP_DELIVERYSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZMM_TANKDIP_DELIVERYSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.32.98/IADMS/zmm_tankdip_delivery.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ZMM_TANKDIP_DELIVERYSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.32.98/IADMS/zmm_tankdip_delivery.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ZMM_TANKDIP_DELIVERYSoap,
            
            ZMM_TANKDIP_DELIVERYSoap12,
        }
    }
}
